apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Production release
        - $patch: replace
        image: quay.io/mavazque/tekton-reversewords:a8a51732295a77f771c5b0a7277e8551c3d99e44
        name: reverse-words
