apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/mavazque/tekton-reversewords:f865b2365accf360cc64e186a3ccec269c5a46b8
        name: reverse-words
