apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/mavazque/tekton-reversewords:43cd43c27feb92991bcf6278c07b3b2a8eefa758
        name: reverse-words
